### ISSUE TITLE
Notes on using this self-hosted (not docker) with Authelia

### ISSUE THREAD

**Issue by vauxia** [fabianmp/taiga-contrib-oidc-auth#2]
I've had a heck of a time getting the various openid / auth modules to work properly with Authelia and my self-hosted Taiga instance, and finally got it all unlocked using this plugin.

Here are the settings that worked (assuming you have downloaded the code, pip-installed the library, and symlinked the javascript plugins into taiga-front):

**taiga-front-dist/dist/conf.js**

```
    "oidcButtonText": "Log in at [my provider name]",
    "oidcMountPoint": "/api/oidc",
    "contribPlugins": [
      "/plugins/oidc-auth/oidc-auth.json"
    ]
```

**taiga-back/settings/config.py**
```
INSTALLED_APPS += [
        "mozilla_django_oidc",
        "taiga_contrib_oidc_auth",
]

AUTHENTICATION_BACKENDS = list(AUTHENTICATION_BACKENDS) + [
        "taiga_contrib_oidc_auth.oidc.TaigaOIDCAuthenticationBackend",
]

# Add the OIDC urls
ROOT_URLCONF = "settings.urls"

# OIDC Settings
OIDC_CALLBACK_CLASS = "taiga_contrib_oidc_auth.views.TaigaOIDCAuthenticationCallbackView"

OIDC_BASE_URL="{BASE_URL}"
OIDC_RP_CLIENT_ID = "{CLIENT_ID}"
OIDC_RP_CLIENT_SECRET = "{CLIENT_SECRET}"
OIDC_RP_SCOPES="openid profile email"  # optionally configure scopes
OIDC_RP_SIGN_ALGO = "RS256"

# optionally configure endpoints
OIDC_OP_AUTHORIZATION_ENDPOINT="{BASE_URL}/api/oidc/authorization"
OIDC_OP_JWKS_ENDPOINT="{BASE_URL}/jwks.json"
OIDC_OP_TOKEN_ENDPOINT="{BASE_URL}/api/oidc/token"
OIDC_OP_USER_ENDPOINT="{BASE_URL}/api/oidc/userinfo"
```

**authelia.yml on auth server**
```
      - client_id: '{CLIENT_ID}'
        client_name: 'Taiga'
        client_secret: '{CLIENT_SECRET}'
        redirect_uris:
          - '{TAIGA_SITE}/login'
          - '{TAIGA_SITE}/api/oidc/callback/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        token_endpoint_auth_method: 'client_secret_post'
        userinfo_signed_response_alg: 'none'
```

Make sure to replace everything in {} with appropriate values. I hope this helps someone!
